### ISSUE TITLE
그라운드 생성

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#13]

**Comment by gene-ss** [comment]
title이랑 만료기간 설정해야하는 것 같은데
어떤 형식으로 만료기간을 받나요?

**Comment by choi5798** [comment]
데이터를 주고 받을 땐 string으로 주고 받고 알아서 파싱해서 쓰는 건 어떨까요?

**Comment by gene-ss** [comment]
@choi5798  네 만료기간을 더한 time format string을 보내겠습니다.
