### ISSUE TITLE
파일 다운로드 명세서 작성 및 구현

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#16]

**Comment by sangeun99** [comment]
다운로드 GET /ground/:gid/photo/:photoid
요청 바디 : client_id=<your_client_id>, client_secret=<your_client_secret>, bucket_name=<aws_s3_bucket_name>
응답 바디 : {"status": "success"}, {"file": "<image_file>"}

**Comment by gene-ss** [comment]
@sangeun99 명세서의 인증 방식은 어디서 나온건가요? 응답 바디로 이미지 파일은 어떻게 넘겨주실 생각인가요? 해당 api는 프론트가 접근해야할텐데 프론트 입장에서는 버킷 이름을 어떻게 알아내나요?

**Comment by sangeun99** [comment]
> 명세서의 인증 방식은 어디서 나온건가요? 응답 바디로 이미지 파일은 어떻게 넘겨주실 생각인가요? 해당 api는 프론트가 접근해야할텐데 프론트 입장에서는 버킷 이름을 어떻게 알아내나요?

- s3 접속 시 필요한 인증 정보를 넣었습니다
- presigned url을 request로 넣으면 응답으로 이미지가 나옵니다. 이 부분 질문하신 거 맞나요? 
- 버킷이 100개까지만 생성되기 때문에 하나의 버킷을 둔다고 생각했습니다. 근데 이렇게 하나의 버킷을 둘 경우에는 요청으로 줄 필요가 없겠네요
