### ISSUE TITLE
파일 업로드 작성 및 구현

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#17]

**Comment by sangeun99** [comment]
업로드 POST /ground/:gid/photo
요청 바디 : client_id=<your_client_id>, client_secret=<your_client_secret>, file=<image_file>, bucket_name=<aws_s3_bucket_name>
응답 바디 : {"status": "success"}

**Comment by sangeun99** [comment]
업로드 작업은 s3접속 (사용자인증) -> s3.generate_presigned_post (presigned url을 생성) -> 해당 요청으로 받아온 응답 내용을 다시 post 하는 작업으로 구현했는데 이 작업을 각각의 post 두 개로 나눌 필요가 있을까요?

**Comment by gene-ss** [comment]
@sangeun99 

> 업로드 POST /ground/:gid/photo 요청 바디 : client_id=<your_client_id>, client_secret=<your_client_secret>, file=<image_file>, bucket_name=<aws_s3_bucket_name> 응답 바디 : {"status": "success"}

다운로드랑 똑같은 질문을 드리고 싶어요.

> 업로드 작업은 s3접속 (사용자인증) -> s3.generate_presigned_post (presigned url을 생성) -> 해당 요청으로 받아온 응답 내용을 다시 post 하는 작업으로 구현했는데 이 작업을 각각의 post 두 개로 나눌 필요가 있을까요?

그러니까 클라이언트에서 s3를 직접 접속하는건가요? 앞 부분은 서버에서 해야할 내용 같습니다.
