### ISSUE TITLE
썸네일 생성 람다

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#19]

**Comment by gene-ss** [comment]
S3의 특정 버킷에 이미지가 업로드 될 경우 해상도를 줄인 이미지를 생성해서 원본과 같은 태그 정보를 유지한채로 `{원본이름}-low` 이런 이름으로 저장 -> 매우 주의해야하는 점 !!!!! 만약 Recursive하게 해상도 줄인 이미지로 인해 또 람다가 발동하면 정말 큰일납니다. 매우 주의 서버비 몇천만원이 청구될 수 있어요. (생각해보니 차라리 버킷을 분리하는 것도 괜찮을 듯 합니다.)

**Comment by joybully** [comment]
계획
1. s3 버킷 생성
2. IAM 정책생성
3. 실행 역할 생성
4. 배포패키지 생성
5. 람다함수 생성
6. 람다 함수 테스트
7. S3업로드
8. 트리거 테스트
9. 리소스 마무리

**Comment by joybully** [comment]
파이썬으로 이미지 썸네일 생성을 위해 PIL패키지를 이용하고자 하여 AWS SAM을 이용해 람다함수 및 패키지를 배포하고자 함

**Comment by joybully** [comment]
SAM을 docker를 활용해 띄우는데 성공, 하지만 배포과정에서 에러가 발생
Error: Failed to create managed resources: An error occurred (AccessDenied) when calling the CreateChangeSet operation: User: arn:aws:iam::845319821319:user/joybully is not authorized to perform: cloudformation:CreateChangeSet on resource: arn:aws:cloudformation:us-east-1:845319821319:stack/aws-sam-cli-managed-default/* because no identity-based policy allows the cloudformation:CreateChangeSet action

**Comment by choi5798** [comment]
https://docs.aws.amazon.com/ko_kr/AWSCloudFormation/latest/UserGuide/aws-properties-iam-accesskey.html

https://docs.aws.amazon.com/ko_kr/IAM/latest/UserGuide/troubleshoot_access-denied.html

https://github.com/aws/serverless-application-model/issues/186

한 번 참고해보세요

**Comment by gene-ss** [comment]
IAM 권한이 없어서 그렇습니다.

**Comment by joybully** [comment]
IAM 권한 해결 완료

**Comment by joybully** [comment]
또 다른 에러 발생

**Comment by joybully** [comment]
C:\Users\Baptist\.aws\lambda-s3>sam deploy --guided

Configuring SAM deploy
======================

        Looking for config file [samconfig.toml] :  Not found

        Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [sam-app]:
        AWS Region [us-east-1]:
        #Shows you resources changes to be deployed and require a 'Y' to initiate deploy
        Confirm changes before deploy [y/N]:
        #SAM needs permission to be able to create roles to connect to the resources in your template
        Allow SAM CLI IAM role creation [Y/n]:
        #Preserves the state of previously provisioned resources when an operation fails
        Disable rollback [y/N]:
        Save arguments to configuration file [Y/n]:
        SAM configuration file [samconfig.toml]:
        SAM configuration environment [default]:

        Looking for resources needed for deployment:
        Creating the required resources...
Error: Failed to create managed resources: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once

**Comment by joybully** [comment]
에러를 해결하기 위해 아래 링크를 참고함
https://github.com/aws/aws-sam-cli/issues/3243
커맨드 라인에 sam delete --stack-name aws-sam-cli-managed-default를 입력 후 다시 들어가서 시도했지만 다시 에러가 발생

**Comment by gene-ss** [comment]
Looking for config file [samconfig.toml] :  Not found

aws문서를 보시고 만들어주세요.
config 파일이 없어서 생기는 것 같습니다.
