### ISSUE TITLE
백엔드 프로젝트 구조 제안

### ISSUE THREAD

**Issue by choi5798** [FileGround-CloudComputing/FileGround-Backend#23]
https://taptorestart.tistory.com/entry/FastAPI-%EB%94%94%EB%A0%89%ED%84%B0%EB%A6%AC-%EA%B5%AC%EC%A1%B0%EB%A5%BC-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%98%EB%8A%94-%EA%B2%8C-%EC%A2%8B%EC%9D%84%EA%B9%8C

위 사이트에서 fastApi 개발자의 프로젝트를 안내하면서 구조를 추천해주고 있습니다
위 구조를 이번 프로젝트에 적용하면 좋을 것 같은데 어떻게 생각하시나요?

**Comment by sangeun99** [comment]
확인했습니다 좋네요!
