### ISSUE TITLE
github action을 활용한 개발환경 배포 자동화

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#27]
## GOAL
- 도커 허브를 이용한 개발환경 배포 자동화

## TODO
- [x] 메인 브랜치 보호하기
- [ ] 메인 브랜치에 푸쉬되면을 트리거로 도커 이미지 빌드 및 푸쉬하는 깃허브 액션 작성

**Comment by choi5798** [comment]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/22406453/230069770-b0537596-de72-4792-a918-d5ebafd3b570.png">
메인 브랜치 보호 룰 적용했습니다
