### ISSUE TITLE
Firebase로의 이전 검토

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#31]

**Comment by sangeun99** [comment]
기존에 aws에서 사용하려고 했던 ecs, s3, lambda, rds 역할을 해줄 firebase 기능 탐색
aws s3는 cloud storage로, lambda는 cloud functions로, aws rds는 firebase realtime database로 이전 가능
aws academy 계정으로 못 하는 작업들 (iam 계정 생성 등) firebase에서는 더 가볍게 우리가 하고자 하는 작업을 할 수 있음을 확인함.
