### ISSUE TITLE
Firebase 유사 서비스 찾기

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#33]
## TODO
- S3
- RDS
- Lambda

**Comment by sangeun99** [comment]
- S3는 Firebase storage로 대체 가능
- RDS는 Firebase realtime Database로 대체 가능
- Lambda는 Firebase cloud functions로 대체 가능

**Comment by gene-ss** [comment]
확인했습니다. 아쉽지만 SQS는 DB와 소켓으로 대체해야할 듯 하네요.
