### ISSUE TITLE
회원가입

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#7]

**Comment by choi5798** [comment]
네이버 소셜로그인 및 회원가입 목업 코드를 작성했는데 소셜로그인을 통해 accessToken을 받아서 그 토큰으로 회원가입을 진행하는 방식으로 짜여졌습니다. api url 이 2개가 생성되었는데 기존 설계와 맞지 않습니다. 회원가입과 소셜로그인 api url을 나누는 것은 어떤가요?

**Comment by gene-ss** [comment]
일단 임시로 하나로 둘 예정입니다.
api의 경우 제가 임시 테스트로 요청을 보내면 refresh토큰을 생성하는 api가 하나 있고( post /auth/refresh ) 
구현 안한 api가 있는데 ( post /auth ) 구현 안한 api가 로그인 url 생성해서 보내주면 됩니다.

**Comment by choi5798** [comment]
로컬에서 네이버 로그인 구현 완료 했습니다
<img width="390" alt="image" src="https://user-images.githubusercontent.com/22406453/230329254-28802858-9a54-4f07-a97e-4992beedc321.png">
<img width="1709" alt="image" src="https://user-images.githubusercontent.com/22406453/230330726-7d1f2176-45d2-44cd-85eb-ae2c40423445.png">
