### ISSUE TITLE
액세스 토큰 갱신

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#9]

**Comment by gene-ss** [comment]
@choi5798  리프레쉬 토큰을 받아야할 것 같은데, 헤더에서 어떤 형식으로 받나요?

**Comment by gene-ss** [comment]
@choi5798 Authroization: Bearer RefreshToken 으로 해주세요. fastapi jwt library에서 이 형식으로 받습니다.

**Comment by choi5798** [comment]
네 참고하겠습니다
